# Basic
title: Young
subtitle: ä¸ªäººç«™
description: æ¬¢è¿æ¥åˆ°æˆ‘çš„ä¸ªäººç«™~

# å¤´åƒé‡Œé¢çš„æ ‡é¢˜
avatarTitle: Young
# å¤´åƒé‡Œé¢çš„æè¿°
avatarDesc: æ•°æ®åˆ†æ
url: ""

# åšå®¢æ˜¯å¦è‡ªåŠ¨ç”Ÿæˆç›®å½•ï¼Œfalseä¸ºä¸ç”Ÿæˆ
enableToc: false

# Comment
comment:
    # livere: # https://www.livere.com
    # disqus:
    # uyan: # æœ‰è¨€id,ç™»å½•æœ‰è¨€å®˜ç½‘ç”³è¯·
    gittalk:
        clientID: b484eaa4dc764b040085
        clientSecret: 7d873d1d5a67242c6fae6a35c1f4cff4bef32960
        repo: PANGZhengyang.github.io
        owner: PANGZhengyang
        admin: PANGZhengyang

# Social
social:
    # weibo:
    # github: Blanket58
    # zhihu: blanket58
    # juejin:
    # jianshu:
    # twitter:
    # mail:


# ç™¾åº¦ç»Ÿè®¡
# ä½¿ç”¨åšå®¢æ¨¡æ¿è¯·å»æ‰æˆ–è€…æ›´æ¢ id
baidu:
    id:35ac4e823ee3c3d7a995456c8d79c67c




# ã€Š----------------- ä¸Šé¢çš„ä¿¡æ¯ä¿®æ”¹æˆä½ è‡ªå·±çš„ ---------------------------ã€‹


#
#  _post/ ä¸‹çš„æ–‡ç« æ›´æ¢æˆä½ è‡ªå·±çš„æ–‡ç« 
#  å¸®å¿™starä¸€ä¸‹ï¼Œæ„Ÿè°¢~ğŸ˜† åœ°å€ï¼š https://github.com/leopardpan/leopardpan.github.io
#
#
# ã€Š--------------- ä¸‹é¢çš„ä¿¡æ¯å¯ä»¥è‡ªè¡Œé€‰æ‹©æ˜¯å¦ä¿®æ”¹ ------------------------ã€‹


permalink: /:year/:month/:title/
# Format
highlighter: rouge

textColor: #FF0000

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: åšå®¢ä¸»é¡µ

# Navigation buttons in the front page.s
nav:
    - {title: æ‰€æœ‰æ–‡ç« , description: archive, url: '/archive'}
    - {title: æ ‡ç­¾, description: tags, url: '/tags'}
    - {title: æŠ€æœ¯æ”¯æŒ, description: support, url: '/support'}
    - {title: å…³äºæˆ‘, description: about, url: '/about'}


# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"
